version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root']
      interval: 5s
      timeout: 2s
      retries: 20
